// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `quality_clamp`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<CompressionResponse> compressImage({
  required CompressionRequest request,
}) => RustLib.instance.api.crateApiImageEngineCompressImage(request: request);

Future<List<CompressionResponse?>> compressImagesBatch({
  required List<CompressionRequest> requests,
}) => RustLib.instance.api.crateApiImageEngineCompressImagesBatch(
  requests: requests,
);

class CompressionRequest {
  final String inputPath;
  final String outputPath;
  final int quality;
  final int pngLevel;
  final int? maxLongEdge;
  final OutputFormat outputFormat;

  const CompressionRequest({
    required this.inputPath,
    required this.outputPath,
    required this.quality,
    required this.pngLevel,
    this.maxLongEdge,
    required this.outputFormat,
  });

  @override
  int get hashCode =>
      inputPath.hashCode ^
      outputPath.hashCode ^
      quality.hashCode ^
      pngLevel.hashCode ^
      maxLongEdge.hashCode ^
      outputFormat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressionRequest &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          outputPath == other.outputPath &&
          quality == other.quality &&
          pngLevel == other.pngLevel &&
          maxLongEdge == other.maxLongEdge &&
          outputFormat == other.outputFormat;
}

class CompressionResponse {
  final String outputPath;
  final int originalBytes;
  final int compressedBytes;

  const CompressionResponse({
    required this.outputPath,
    required this.originalBytes,
    required this.compressedBytes,
  });

  @override
  int get hashCode =>
      outputPath.hashCode ^ originalBytes.hashCode ^ compressedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressionResponse &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          originalBytes == other.originalBytes &&
          compressedBytes == other.compressedBytes;
}

enum OutputFormat { jpeg, png }
